### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/comet_cms#5]
- [x] © and Author fields
- [x] Font Awesome icons for the toolbar
- [x] make the content box more noticeable
- [x] meta box is too large (hidden by default)
- [x] change_view does not work
- [x] user database
- [x] password changing
- [x] user add/delete
- [x] leverage `author` field
- [x] cookie-based auth
- [x] saner new post/page modals → now a simple form on index
- [x] post deletion modals
- [x] user deletion modals
